# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/ravenskrag/Experiments/OpenFrameworks/of_v0.9.3_libs/custom/poco/poco-1.7.4-all
POCO_BUILD = /home/ravenskrag/Experiments/OpenFrameworks/of_v0.9.3_libs/custom/poco/poco-1.7.4-all
POCO_FLAGS = 
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL MongoDB PDF CppParser
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
export LINKMODE
